import Head from "next/head";
import styles from "@/styles/layout.module.css";
import { Roboto } from "@next/font/google";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Spetz Frontend Mentor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${roboto.className}`}>{children}</main>
    </>
  );
}
